// Real roster from coastalwellness.net/meet-our-team — bios, credentials,
// insurance panels, offices, days, availability and headshots are all the
// practice's own. `photo` is the image's filename on their CDN, resolved via
// `staffPhoto()`; at handoff these should be re-uploaded to the new host
// rather than hotlinked from the old site.

export type Population =
  | "Children"
  | "Teens"
  | "Adults"
  | "Couples"
  | "Families";

export type Office = "Suntree" | "Eau Gallie" | "Telehealth";

export type Clinician = {
  id: string;
  name: string;
  credentials: string;
  title?: string;
  insurance: string;
  offices: Office[];
  days: string;
  /** null = accepting now; a string = the month they open up. */
  waitlist: string | null;
  accepting: boolean;
  languages: string[];
  populations: Population[];
  /** Presenting concerns — shown as chips on the card. */
  focus: string[];
  /** Trainings, certifications and modalities — shown when the bio is open. */
  modalities: string[];
  bio: string;
  /** Headshot filename on the practice's CDN — see `staffPhoto()`. */
  photo: string;
};

export const clinicians: Clinician[] = [
  {
    id: "neeley-hughey",
    name: "Dr. Neeley Hughey",
    credentials: "PhD, LPC, LMHC, QS",
    title: "Clinical Director & Founder",
    insurance: "Aetna, Cigna, BC/BS",
    offices: ["Suntree", "Telehealth"],
    days: "Mon & Thu telehealth · Tue & Wed in person",
    waitlist: "January 2027",
    accepting: true,
    languages: ["English"],
    populations: ["Adults"],
    focus: ["Trauma & PTSD", "Military & Veterans", "First Responders"],
    modalities: [
      "EMDRIA Approved EMDR Consultant",
      "EMDR Intensives",
      "IFS (Level 3)",
      "TF-CBT",
      "Somatic Therapy",
      "CCTP",
      "NERPSC Certified",
    ],
    bio: "Neeley founded Coastal Wellness after a 16-year career with the Department of Defense and brings more than 25 years of clinical experience to her work with military members, veterans and first responders. Licensed in both Florida and Virginia, she specializes in PTSD and complex PTSD, and offers EMDR Intensives alongside weekly sessions. She is also an EMDRIA Approved Consultant, supervising and certifying other clinicians in EMDR.",
    photo: "9A1000E5-D0B4-4DAF-91E7-DD39E0B0E989-1920w.png",
  },
  {
    id: "erin-arbour",
    name: "Erin Arbour",
    credentials: "Registered Mental Health Counselor Intern",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Eau Gallie", "Suntree"],
    days: "Tue, Wed, Thu, Fri",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples"],
    focus: ["Trauma & PTSD", "Addiction", "Anxiety", "Depression"],
    modalities: ["EMDRIA Approved EMDR", "Gottman Levels 1 & 2"],
    bio: "With more than six years in the field, Erin works with teens, adults and couples on trauma, PTSD, addiction, anxiety and depression. She is trained in Gottman Levels 1 and 2 for couples work and uses EMDR for trauma processing.",
    photo: "coastal-wellness-and-life-coaching-center-erin-arbour-01-1920w.jpg",
  },
  {
    id: "lisa-arnabat",
    name: "Lisa Arnabat",
    credentials: "MS, LMHC",
    insurance: "Aetna, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon, Tue, Wed, Fri",
    waitlist: null,
    accepting: true,
    languages: ["English", "German"],
    populations: ["Teens", "Adults"],
    focus: ["Eating Disorders", "Self-Harm", "Trauma"],
    modalities: [
      "CCTP",
      "Internal Family Systems",
      "Accelerated Resolution Therapy",
      "Nutritional Coaching",
    ],
    bio: "Lisa has 15 years of experience and works with adolescents and adults around eating disorders, self-harm and trauma. A Certified Clinical Trauma Professional trained in IFS and ART, she also integrates nutritional coaching into her work.",
    photo: "coastal-wellness-and-life-coaching-center-lisa-arnabat-1920w.jpg",
  },
  {
    id: "trish-bruner",
    name: "Trish Bruner",
    credentials: "MA, RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon, Tue, Wed, Fri",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English", "Portuguese"],
    populations: ["Children", "Teens", "Families", "Adults"],
    focus: ["Children & Teens", "Women's Issues", "Family Dynamics"],
    modalities: [
      "Play Therapy",
      "CBT",
      "Family Systems",
      "Attachment-Based",
      "Narrative Therapy",
      "Solution-Focused",
      "EMDR",
    ],
    bio: "Trish brings over nine years of work with children, teens and families, as well as women 18 and older. She draws on play therapy, CBT, family systems, attachment and narrative approaches, and EMDR, and sees clients in English and Portuguese.",
    photo: "coastal-wellness-and-life-coaching-center-trish-bruner-1920w.jpg",
  },
  {
    id: "angela-bryan",
    name: "Angela Bryan",
    credentials: "MS, LMHC",
    insurance: "Aetna & BC/BS",
    offices: ["Suntree"],
    days: "Tue – Thu",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English", "Spanish", "German"],
    populations: ["Children", "Teens", "Adults"],
    focus: ["Complex Trauma", "Attachment", "Children & Teens"],
    modalities: [
      "TBRI",
      "EMDR",
      "TF-CBT",
      "DBT",
      "Art Therapy",
      "Polyvagal-Informed",
      "Somatic Therapy",
      "IFS",
    ],
    bio: "Angela has more than 20 years of experience treating complex trauma in children, teens and adults. She is TBRI-trained and works across EMDR, TF-CBT, DBT, art therapy and somatic and polyvagal-informed approaches, in English, Spanish and German.",
    photo: "coastal-wellness-and-life-coaching-center-angela-bryan-1920w.jpg",
  },
  {
    id: "dana-chesser",
    name: "Dana Chesser",
    credentials: "MA",
    title: "Pre-Licensed Counselor",
    insurance: "Discounted self-pay rates",
    offices: ["Eau Gallie"],
    days: "Wed, Fri",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples", "Families"],
    focus: ["Anxiety", "Life Transitions", "Family Conflict"],
    modalities: ["CBT"],
    bio: "Dana spent more than 20 years as an educator before moving into counseling, and now works with teens, adults, couples and families using CBT. As a pre-licensed counselor she offers discounted self-pay rates.",
    photo: "coastal-wellness-and-life-coaching-center-dana-chesser-1920w.jpg",
  },
  {
    id: "colleen-easterlin",
    name: "Colleen Easterlin",
    credentials: "MS, LMFT",
    insurance: "Aetna, BC/BS, Curative",
    offices: ["Suntree"],
    days: "Mon, Thu",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Adults", "Couples"],
    focus: ["Couples & Marriage", "Communication", "Connection"],
    modalities: ["Gottman Level 2", "Emotionally Focused Therapy"],
    bio: "Colleen is a licensed marriage and family therapist with more than 16 years of experience. She works with adults and couples using Gottman Level 2 training and Emotionally Focused Therapy.",
    photo: "coastal-wellness-and-life-coaching-center-colleen-easterlin-02-1920w.jpg",
  },
  {
    id: "corinne-edwards",
    name: "Corinne Edwards",
    credentials: "RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon, Tue, Thu, Fri",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Children", "Teens", "Adults", "Families"],
    focus: ["Children 4+", "Young Adults", "Parenting Support"],
    modalities: [
      "CBT",
      "DBT",
      "Choice Theory",
      "Expressive Arts",
      "Play Therapy",
    ],
    bio: "Corinne works with children from age four through young adulthood, as well as families and parents. She blends CBT, DBT and Choice Theory with expressive arts and play therapy to meet each client where they are.",
    photo: "corinne-edwards-coastal-wellness-and-life-coaching-center-1920w.jpg",
  },
  {
    id: "kelly-hendricks",
    name: "Kelly Hendricks",
    credentials: "M.A., Registered MFT Intern",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Tue, Wed, Thu, Sat",
    waitlist: "January 2027",
    accepting: true,
    languages: ["English"],
    populations: ["Adults", "Couples"],
    focus: ["Couples", "Infidelity", "Premarital Counseling"],
    modalities: [
      "Prepare-Enrich",
      "Gottman Level 2",
      "Emotionally Focused Therapy",
    ],
    bio: "Kelly has worked in the field since 2010 and focuses on couples — including infidelity recovery and premarital counseling. She is a Prepare-Enrich facilitator with Gottman Level 2 and EFT training.",
    photo: "coastal-wellness-and-life-coaching-center-kelly-hendricks-1920w.jpg",
  },
  {
    id: "taylor-kilpatrick",
    name: "Taylor Kilpatrick",
    credentials: "M.S.W., Registered Clinical Social Work Intern",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Eau Gallie", "Suntree"],
    days: "Mon, Wed, Thu, Sat",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples"],
    focus: ["Substance Use", "Medical Trauma", "Chronic Illness"],
    modalities: [
      "EMDRIA Approved EMDR",
      "CBT",
      "DBT",
      "Motivational Interviewing",
    ],
    bio: "Taylor brings more than five years of experience with substance use, medical trauma and chronic illness. They work with adolescents from age 13, adults and couples using CBT, DBT, motivational interviewing and EMDR.",
    photo: "coastal-wellness-and-life-coaching-center-taylor-kilpatrick-1920w.jpg",
  },
  {
    id: "jackie-marinaro",
    name: "Jackie Marinaro",
    credentials: "RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Eau Gallie", "Suntree"],
    days: "Mon, Tue, Wed, Sat",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples"],
    focus: ["PTSD & C-PTSD", "OCD", "Grief", "Sexual Assault"],
    modalities: ["Certified Clinical Hypnotherapist"],
    bio: "Jackie has more than 15 years of experience with PTSD and complex PTSD, anxiety, depression, OCD, grief and sexual assault recovery. She is also a Certified Clinical Hypnotherapist and sees adolescents from age 12, adults and couples.",
    photo: "jackie-marinaro-coastal-wellness-and-life-coaching-center-1920w.jpg",
  },
  {
    id: "miranda-moses",
    name: "Miranda Moses",
    credentials: "MA, LMHC",
    title: "Senior Therapist",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Eau Gallie", "Suntree"],
    days: "Mon – Thu",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English"],
    populations: ["Adults"],
    focus: ["Trauma", "Grief", "Codependency", "Intimate Partner Violence"],
    modalities: ["EMDRIA Certified EMDR", "TF-CBT", "IFS"],
    bio: "Miranda is a senior therapist with 12 years of experience working with adults on depression, anxiety, trauma, grief, codependency and intimate partner violence. She is EMDRIA Certified and also draws on TF-CBT and Internal Family Systems.",
    photo: "coastal-wellness-and-life-coaching-center-miranda-moses-1920w.jpg",
  },
  {
    id: "mary-paisley",
    name: "Mary Paisley",
    credentials: "MA, LMHC",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon – Thu",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Adults", "Couples"],
    focus: ["Anxiety", "Trauma", "Grief", "Couples"],
    modalities: [
      "EMDRIA Certified EMDR",
      "EMDR Consultant in Training",
      "ACT",
      "DBT",
      "CBT",
      "Gottman Method",
    ],
    bio: "Mary works with adults on anxiety, trauma and grief, and with couples using the Gottman Method. She is EMDRIA Certified and an EMDR Consultant in Training, and integrates ACT, DBT and CBT into her practice.",
    photo: "mary-paisley-coastal-wellness-and-life-coaching-center-1920w.jpg",
  },
  {
    id: "evan-rojas",
    name: "Evan Rojas",
    credentials: "MA, LMHC, NCC",
    insurance: "Aetna, BC/BS, Cigna",
    offices: ["Telehealth"],
    days: "Tue, Wed, Thu",
    waitlist: null,
    accepting: false,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples", "Families"],
    focus: ["Veterans", "Dual Diagnosis", "Criminal Justice"],
    modalities: [
      "Motivational Interviewing",
      "CBT",
      "ACT",
      "Mindfulness",
      "EMDR",
      "Gottman Level 2",
    ],
    bio: "Evan is a Nationally Certified Counselor with nine years of experience across criminal justice settings, veteran care and dual diagnosis. He sees teens, adults, couples and families by telehealth only, working from motivational interviewing, CBT, ACT, mindfulness and EMDR.",
    photo: "coastal-wellness-and-life-coaching-center-evan-rojas-1920w.jpg",
  },
  {
    id: "tara-roberts-tiflati",
    name: "Tara Roberts-Tiflati",
    credentials: "MA, RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Eau Gallie", "Suntree"],
    days: "Mon, Wed, Fri",
    waitlist: null,
    accepting: false,
    languages: ["English"],
    populations: ["Teens", "Adults"],
    focus: ["Anxiety", "Depression", "Self-Esteem", "Life Transitions"],
    modalities: ["CBT", "Solution-Focused Therapy", "Mindfulness"],
    bio: "Tara spent seven years in school settings before moving into private practice, and works with teens and adults on anxiety, depression, self-esteem and life transitions using CBT, solution-focused therapy and mindfulness.",
    photo: "coastal-wellness-and-life-coaching-center-tara-roberts-tiflati-1920w.jpg",
  },
  {
    id: "sarah-stupp",
    name: "Sarah Stupp",
    credentials: "MSEd, RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon, Wed, Thu, Sun",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults", "Couples"],
    focus: ["LGBTQ+ & Gender-Affirming", "PTSD & C-PTSD", "Anxiety"],
    modalities: [
      "EMDR",
      "Gottman Level 2",
      "Kink-Informed",
      "Non-Monogamy Affirming",
    ],
    bio: "Sarah worked for 11 years in hospitals and emergency medicine before moving into therapy. Her practice is queer, gender-affirming and kink-informed, and she works with non-monogamous and queer couples as well as adolescents and adults on PTSD, complex PTSD, anxiety and depression.",
    photo: "coastal-wellness-and-life-coaching-center-sarah-stupp-1920w.jpg",
  },
  {
    id: "ariel-wilson",
    name: "Ariel Wilson",
    credentials: "MA, LMHC",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree", "Telehealth"],
    days: "Tue, Thu, Fri in person · Wed telehealth",
    waitlist: "October 2026",
    accepting: true,
    languages: ["English"],
    populations: ["Adults", "Couples"],
    focus: ["Substance Use", "Trauma", "Relationships", "Parenting"],
    modalities: [
      "EMDRIA Certified EMDR",
      "IFS",
      "TF-CBT",
      "DBT",
      "Emotionally Focused Couples Therapy",
      "Gottman Method",
    ],
    bio: "Ariel has practiced since 2014 and works with adults and couples on substance use, trauma, relationships and parenting. She is EMDRIA Certified and also draws on IFS, TF-CBT, DBT, EFCT and the Gottman Method.",
    photo: "coastal-wellness-and-life-coaching-center-ariel-wilson-1920w.jpg",
  },
  {
    id: "garrett-works",
    name: "Garrett Works",
    credentials: "MS, RMHCI",
    insurance: "Aetna PPO & BC/BS, Cigna, Curative",
    offices: ["Suntree"],
    days: "Mon, Fri, Sat",
    waitlist: null,
    accepting: true,
    languages: ["English"],
    populations: ["Teens", "Adults"],
    focus: ["ADHD & Neurodiversity", "Burnout", "Anxiety", "Self-Esteem"],
    modalities: [
      "Neurodiversity Specialist (PESI)",
      "CBT",
      "DBT",
      "IFS",
      "Person-Centered",
    ],
    bio: "Garrett is a PESI-certified Neurodiversity Specialist working with teens and adults on anxiety, depression, ADHD, burnout and self-esteem. His approach combines CBT, DBT, IFS and person-centered therapy.",
    photo: "garrett-works-coastal-wellness-and-life-coaching-1920w.png",
  },
];

export type StaffMember = {
  id: string;
  name: string;
  role: string;
  photo: string;
};

export const officeStaff: StaffMember[] = [
  {
    id: "krys-maciorowski",
    name: "Krys Maciorowski",
    role: "Office Manager",
    photo: "krys-maciorowski-coastal-wellness-and-life-1920w.jpg",
  },
  {
    id: "jen-strait",
    name: "Jen Strait",
    role: "Assistant Office Manager",
    photo: "jen-strait-coastal-wellness-and-life-1920w.jpg",
  },
  {
    id: "sheila-orbe",
    name: "Sheila Orbe",
    role: "Office Assistant",
    photo: "sheila-orbe-coastal-wellness-and-life-1920w.jpg",
  },
  {
    id: "shen-calape",
    name: "Shen Calape",
    role: "Office Assistant",
    photo: "shen-calape-coastal-wellness-and-life-coaching-c187aa10-1920w.png",
  },
  {
    id: "toni-burak",
    name: "Toni Burak",
    role: "Office Assistant",
    photo: "toni-burak-coastal-wellness-and-life-1920w.jpg",
  },
];
